language: python
python:
  - "3.5"
# command to run tests
before_install:
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - python3 -m unittest
  - coverage run -m unittest discover
after_success:
  - coveralls
